{
    "root": {
        "Dresses": {       
            "Size": "fix",
            "Material": [
                "Chiffon",
                "Dobby",
                "Embroidery",
                "Viscose, Jersey",
                "Voile",
                "Crêpe, Satin",
                "Cotton, Muslin",
                "Coated Fabric",
                "Poplin",
                "Cotton, Poplin",
                "Seersucker",
                "Crêpe, Mesh, Satin",
                "Aluminum Alloy",
                "Cotton, Twill",
                "Cotton, Lace",
                "Sequins",
                "Crêpe",
                "Silk",
                "Knitwear",
                "Wool-Like Fabric",
                "Cotton, Jersey",
                "Flocking",
                "Corduroy",
                "Suedette",
                "Tweed",
                "Flannelette",
                "Cotton, Canvas",
                "Viscose",
                "Twill",
                "Cotton, Crêpe",
                "Muslin",
                "Cotton",
                "Chiffon, Crêpe",
                "Mesh Fabric",
                "Linen",
                "Woven Fabric",
                "Viscose, Crêpe",
                "Metallic",
                "Fabric",
                "Scuba",
                "Composite Fabric",
                "Lace",
                "Jersey",
                "Satin",
                "Bouclé",
                "Denim",
                "Lyocell",
                "Rib knit",
                "Cotton, Denim",
                "Jersey, Mesh",
                "The Special Effect Printing",
                "Mesh",
                "Organza",
                "PU material",
                "Knitted Fabric",
                "Velvet",
                "PU Leather",
                "Cotton, Dobby",
                "French Terry"
            ],
            "Fit": [
                "Loose fit",
                "Regular fit",
                "Oversized",
                "Slim fit"
            ],
            "Length": [
                "Knee length",
                "Cropped, Long",
                "Long",
                "Maxi",
                "Midi",
                "Mini",
                "Knee Length",
                "Short"
            ],
            "Style": "fix",
            "Common generic name": [
                "Blazer",
                "Jacket",
                "SWEATSHIRT",
                "Dress"
            ],
            "Neckline": [
                "Queen Anne Neckline",
                "Deep neckline, V-neck",
                "Scoop Neck",
                "Peak Lapels",
                "Cowl Neck",
                "Asymmetric neckline",
                "Round neck",
                "Notched",
                "Funnel Neck",
                "High Neck",
                "Polo",
                "Waterfall",
                "Peter Pan Collar",
                "Deep-plunge neckline, Round neck",
                "Square Neck",
                "Halter",
                "Turtleneck",
                "Tie Neck",
                "Sweetheart neckline",
                "Deep-plunge neckline, Round neck, Sweetheart neckline",
                "Crew-neck",
                "Cowl neck, Deep neckline",
                "Halterneck, Square neckline",
                "Stand Collar",
                "V neck",
                "Hooded",
                "Deep V Neck",
                "Deep-plunge neckline, V-neck",
                "Cowl neck",
                "Polo-neck",
                "Straps",
                "Lapel",
                "Round Neck",
                "Pile Heap Collar",
                "V-neck",
                "Deep neckline",
                "Spaghetti Strap",
                "Deep neckline, Round neck",
                "Boat Neck",
                "Keyhole Neckline",
                "Shawl Collar",
                "Strapless",
                "Overlap Collar",
                "Shirt Collar",
                "Deep-plunge neckline, Halterneck, V-neck",
                "Sweetheart",
                "Halterneck",
                "Asymmetrical Neck",
                "Collar",
                "Off the Shoulder",
                "Deep-plunge neckline",
                "Square neckline",
                "Boat neck"
            ],
            "Collection": [
                "H&M Studio Collection",
                "H&M x Wicked",
                "A/W 2024",
                "HOLIDAY 2024"
            ],
            "Sleeve Style": [
                "Raglan sleeve",
                "Puff sleeve, Raglan sleeve",
                "Butterfly sleeve",
                "Trumpet sleeve",
                "Balloon sleeve, Puff sleeve",
                "Flutter sleeve",
                "Butterfly sleeve, Raglan sleeve",
                "Puff sleeve",
                "Cap sleeve",
                "Balloon sleeve",
                "Balloon sleeve, Raglan sleeve"
            ],
            "Sleeve Length": [
                "Short sleeve",
                "Wrist-Length Sleeve",
                "Sleeveless",
                "Extra-Long Sleeve",
                "Short Sleeve",
                "Cap Sleeve",
                "Three Quarter Length Sleeve",
                "Half Sleeve",
                "Long sleeve, Sleeveless",
                "Long sleeve",
                "Long Sleeve",
                "3/4 sleeve",
                "Extra long sleeve"
            ],
            "Nice to know": [
                "Built-in bra, Removable pads",
                "Lined",
                "H&M Premium Selection",
                "With pocket"
            ], # name chg
            "Collar": [
                "Band collar",
                "Notch lapels",
                "Peter Pan collar",
                "Stand collar",
                "Peak lapels",
                "Resort collar",
                "Bow collar, Stand collar",
                "Open collar",
                "Funnel collar",
                "Bow collar",
                "Cutaway collar",
                "Frilled collar, Stand collar",
                "Shawl lapels",
                "High collar",
                "Frilled collar, Band collar",
                "Frilled collar",
                "Turn-down collar"
            ],
            "Color": "fix",
            "Sleeve Type": [
                "Drop Shoulder",
                "Cold Shoulder",
                "Batwing Sleeve",
                "Flounce Sleeve",
                "Petal Sleeve",
                "Flare Sleeve",
                "Flounce Sleeve, Flare Sleeve",
                "Leg-of-mutton Sleeve",
                "Arm Sleeves",
                "Cloak Sleeve",
                "Split Sleeve",
                "Layered Sleeve",
                "Puff Sleeve",
                "Roll Up Sleeve",
                "Flounce Sleeve, Regular Sleeve",
                "Bishop Sleeve",
                "Regular Sleeve",
                "Raglan Sleeve"
            ],
            "Hem Shaped": [
                "Wrap",
                "Pencil",
                "Ball Gown",
                "Layered/Tiered",
                "Regular",
                "Pleated",
                "Mermaid",
                "Asymmetrical",
                "Straight",
                "Slit",
                "Flared",
                "Flounce"
            ],
            "Waist Line": [
                "Drop Waist",
                "High Waist",
                "Natural",
                "High Waist, Natural"
            ],
            "Type": [
                "Pinafore, Tank",
                "Kaftan",
                "Tank",
                "Shirt, Smock",
                "Shirt",
                "A Line, Bodycon, Fitted",
                "A Line, Cami, Fitted",
                "A Line, Tunic",
                "Pinafore, Bodycon",
                "A Line, Tunic, Fitted",
                "Pinafore, Tunic, Tank",
                "A Line, Fitted",
                "Tank, Bodycon, Fitted",
                "A Line, Smock",
                "Tee",
                "Tunic, Fitted",
                "A Line",
                "Pinafore",
                "Tank, Cami",
                "Bodycon, Fitted",
                "Bodycon, Cami, Fitted",
                "A Line, Cami",
                "Tee, Fitted",
                "Cami, Fit and Flare",
                "A Line, Cami, Fit and Flare",
                "Smock",
                "Fit and Flare",
                "Cami",
                "Tank, Fitted",
                "A Line, Pinafore, Fit and Flare",
                "Tee, A Line, Smock",
                "Pinafore, Cami",
                "Tee, A Line",
                "Fitted",
                "Tank, Bodycon",
                "A Line, Shirt",
                "Tunic",
                "Top",
                "A Line, Tank",
                "A Line, Tank, Fitted",
                "Shirt, Fitted",
                "Tee, Tunic, Fitted",
                "A Line, Shirt, Tunic",
                "A Line, Bodycon",
                "Bodycon",
                "Tee, Bodycon, Fitted",
                "Shirt, Tunic",
                "Bodycon, Cami",
                "Tunic, Tank",
                "Tunic, Bodycon, Fitted",
                "Cami, Fitted",
                "Tee, A Line, Tunic",
                "Tunic, Fit and Flare",
                "A Line, Pinafore, Tank",
                "A Line, Fit and Flare",
                "A Line, Pinafore, Fitted",
                "Tee, Tunic",
                "Shirt, Bodycon"
            ],
            "Details": "fix",
            "Fit Type": [
                "Loose",
                "Slim Fit",
                "Regular Fit",
                "Oversized"
            ],
            "Pattern Type": "fix",
            "Fabric": [
                "Non-Stretch, Slight Stretch",
                "Medium Stretch, Non-Stretch",
                "Slight Stretch",
                "Slight Stretch, Medium Stretch",
                "Medium Stretch, Non-Stretch, Slight Stretch",
                "Medium Stretch, Slight Stretch",
                "Non-Stretch",
                "High Stretch, Medium Stretch",
                "Non-Stretch, High Stretch",
                "Slight Stretch, High Stretch",
                "Medium Stretch",
                "Medium Stretch, High Stretch",
                "High Stretch"
            ],
            "Sheer": [
                "Yes",
                "No",
                "Semi-Sheer"
            ],
            "Body": [
                "Lined top, unlined bottom",
                "Lined",
                "Yes, Lined top, unlined bottom",
                "No",
                "Yes",
                "No, Unlined",
                "Yes, Lined",
                "Unlined",
                "Unlined top, lined bottom"
            ],
            "Pockets": [
                "Yes",
                "Fake Pockets",
                "No"
            ],
            "Occasion": [
                "Beach, Night Out, Office, Home, Street",
                "Beach, Night Out",
                "Night Out, Garden",
                "Night Out, Wedding, Home, Street",
                "Night Out, Office, Street",
                "Beach, Night Out, Home",
                "Beach, Office, Home, Street",
                "Beach",
                "Beach, Night Out, Office, Photoshoot, Street",
                "Beach, Night Out, Wedding, Garden, Street",
                "Beach, Night Out, Wedding, Office, Home, Garden",
                "Night Out",
                "Beach, Night Out, Wedding, Office, Home, Baby Shower Party",
                "Beach, Night Out, Wedding, Office, Home, Garden, Street",
                "Beach, Office, Home",
                "Beach, Night Out, Photoshoot, Street",
                "Office, Street",
                "Garden",
                "Night Out, Street",
                "Beach, Night Out, Babymoon, Garden",
                "Beach, Night Out, Office, Home, Garden",
                "Beach, Night Out, Wedding, Office, Street",
                "Night Out, Office, Garden",
                "Night Out, Wedding, Office, Home, Garden, Street",
                "Night Out, Office, Home",
                "Office",
                "Beach, Night Out, Wedding",
                "Night Out, Wedding, Office, Home, Street",
                "Beach, Garden",
                "Beach, Night Out, Street",
                "Beach, Night Out, Garden",
                "Beach, Night Out, Wedding, Street"
            ],
            "Lined For Added Warmth": [
                "Yes",
                "No"
            ],
            "Belt": [
                "Yes",
                "No"
            ],
            "Features": [
                "Great quality, Soft & Lightweight",
                "Comfortable, Lightweight",
                "Great quality, Stretch",
                "Lightweight, Soft",
                "Great quality, Skin-friendly, Long-Lasting, Soft & Lightweight, Warm & Breathable",
                "Great quality, Comfortable, Lightweight",
                "High Stretch",
                "Breathable, Lightweight, Cooling, Soft & Lightweight",
                "Stretch, Maximum Comfort",
                "Great quality, Comfortable, Stretch, Soft, High Stretch",
                "Great quality, Soft & Lightweight, Soft",
                "Skin-friendly, Soft",
                "Breathable, Lightweight, High Stretch",
                "Cooling, Soft",
                "Lightweight",
                "Great quality, Comfortable, Maximum Comfort, Skin-friendly, Long-Lasting",
                "Great quality",
                "Anti Wrinkle",
                "Great quality, Comfortable",
                "High Stretch, Stretch, Soft, Comfortable, Great quality",
                "Comfortable",
                "Great quality, Skin-friendly",
                "Great quality, Maximum Comfort, Soft & Lightweight",
                "Skin-friendly",
                "Comfortable, Breathable",
                "Long-Lasting",
                "Soft",
                "Breathable",
                "Ojocreat",
                "Great quality, Comfortable, Soft & Lightweight",
                "Breathable, Lightweight",
                "Feels Like Skin",
                "Great quality, Maximum Comfort"
            ],
            "Chest pad": [
                "Yes",
                "No Padding"
            ],
            "Special Features": [
                "Forest-Safe Fibers",
                "Rescued Material",
                "Recycled Material",
                "Recycled Material, Forest-Safe Fibers"
            ],
            "Dresses Material": [
                "Woven Fabric",
                "Knitted Fabric, Knitted Fabric, Knitted Fabric",
                "Fabric",
                "Organza",
                "Knitted Fabric, Knitted Fabric",
                "Fabric, Fabric, Fabric, Fabric",
                "Lace, Lace",
                "Woven Fabric, Woven Fabric",
                "Lace",
                "Knitted Fabric",
                "Satin",
                "Mesh Fabric"
            ], # name chg
            "Dresses Sleeve Length": [
                "Sleeveless, Sleeveless",
                "Long Sleeve",
                "Sleeveless",
                "Sleeveless, Three Quarter Length Sleeve",
                "Sleeveless, Long Sleeve",
                "Short Sleeve",
                "Sleeveless, Sleeveless, Sleeveless",
                "Long Sleeve, Sleeveless",
                "Wrist-Length Sleeve",
                "Long Sleeve, Long Sleeve"
            ], # name chg
            "Dresses Length": [
                "Long",
                "Short, Short, Short",
                "Maxi",
                "Midi",
                "Mini, Mini",
                "Short, Short",
                "Short, Mini",
                "Short"
            ], # name chg
            "Outerwear Length": [
                "Crop",
                "Long"
            ], 
            "Outerwear Body": [
                "Lined",
                "Unlined"
            ],
            "Outerwear Material": [
                "Knitted Fabric",
                "Fabric",
                "Lace"
            ]
        },
        "Skirts": {
            "Skirts Length": [
                "Short",
                "Maxi"
            ],
            "Skirts Material": [
                "Woven Fabric",
                "Organza"
            ]
        }, # extract by dresses
        "Gloves": {
            "Gloves Material": [
                "Polyester",
                "Lace"
            ]
        }, # extract by dresses
        "tops": {
            "Tops Length": [
                "Regular",
                "Long"
            ]
        } # extract by dresses
    }
}