Jeans= {
    "Composition": "fix",  # add
    "Color": "fix",  # add
    "Material": [
        "Wool",
        "Chiffon",
        "Embroidery",
        "Glitter",
        "Polyester",
        "Stainless Steel",
        "Coated Fabric",
        "Faux Fur",
        "Imitation Denim Print",
        "Knitwear",
        "Wool-Like Fabric",
        "PET",
        "Polyamide",
        "Tweed",
        "Viscose",
        "Cotton",
        "Canvas",
        "Linen",
        "Woven Fabric",
        "Fabric",
        "Denim",
        "Cotton, Denim",
        "Knitted Fabric",
        "PU Leather",
        "Composite Fabric",
        "Corduroy"
    ],
    "Waist Line": [
        "High Waist",
        "Ultra Low Waist",
        "Drop Waist",
        "Ultra High Waist",
        "Natural"
    ],
    "Type": "fix",  # add
    "Fit Type": [
        "Oversized",
        "Skinny",
        "Loose",
        "Slim Fit",
        "Regular Fit"
    ],
    "Belt": [
        "Yes",
        "No"
    ],
    "Length": [
        "Capris",
        "Mini Shorts",
        "Long",
        "Regular",
        "Extra Long",
        "Maxi",
        "Cropped",
        "Midi",
        "Extra-long legs",
        "Knee Length",
        "Ankle-length",
        "Thigh Length",
        "Micro Crop",
        "Mini",
        "Mid-Calf",
        "Bermuda shorts",
        "Crop",
        "Short"
    ],
    "Pattern Type": "fix",  # add
    "Features": [
        "Great quality, Stretch, Soft",
        "Great quality, Comfortable, Lightweight",
        "Great quality, Stretch, Skin-friendly",
        "Comfortable, Great quality, Soft, Lightweight, Skin-friendly",
        "Comfortable, Great quality, Lightweight",
        "Comfortable, Great quality, Breathable, Skin-friendly",
        "Warming, Absorbs Sweat, Breathable",
        "Soft, Skin-friendly",
        "Comfortable, Great quality, Long-Lasting",
        "Great quality, Soft",
        "Great quality, Warming, Soft",
        "Comfortable, Long-Lasting",
        "Comfortable, Great quality, Breathable",
        "Comfortable, Great quality, 4-Way Stretch",
        "Stretch",
        "Comfortable, Great quality, Stretch, 4-Way Stretch",
        "Comfortable, Breathable, Soft, Lightweight",
        "Comfortable, Great quality, Breathable, Lightweight",
        "Comfortable, Great quality, Stretch",
        "Great quality, Stretch",
        "Comfortable, Great quality, Skin-friendly",
        "Great quality, Cooling, Stretch, Soft, Skin-friendly, Long-Lasting",
        "Breathable, Comfortable",
        "Comfortable, Great quality, Breathable, Soft, Skin-friendly, Long-Lasting",
        "Comfortable, Great quality",
        "Wind-Proof, Warming, Great quality, Anti Wrinkle",
        "Soft, Non See-Through",
        "Great quality, Warming, Long-Lasting",
        "Great quality, Long-Lasting",
        "Comfortable, Stretch, Soft",
        "Comfortable, Great quality, Wind-Proof, Breathable, Soft",
        "Comfortable, Great quality, 4-Way Stretch, Non See-Through",
        "Comfortable, Great quality, Soft, 4-Way Stretch",
        "Comfortable, Great quality, Breathable, Stretch",
        "Breathable, Soft, Lightweight",
        "Comfortable, Great quality, Warming, Stretch",
        "Breathable",
        "Comfortable, Great quality, Soft, Crochet, Lightweight",
        "Comfortable, Absorbs Sweat, Lightweight",
        "Warming, Comfortable, Great quality",
        "Great quality, Comfortable, Soft",
        "Comfortable, Great quality, Breathable, Skin-friendly, Long-Lasting",
        "Comfortable, Great quality, Wind-Proof, Soft",
        "Comfortable, Breathable, Stretch, Soft",
        "Comfortable, Great quality, Long-Lasting, Soft",
        "Comfortable, Great quality, Long-Lasting, Soft, Lightweight",
        "Stretch, Lightweight",
        "Comfortable, Great quality, Stretch, Soft",
        "Soft, Great quality",
        "Warming, 100% Natural, Comfortable",
        "Comfortable, Wind-Proof",
        "Lightweight",
        "Comfortable, Great quality, Stretch, Long-Lasting",
        "Comfortable, Soft",
        "Comfortable, Great quality, Warming, Soft, Long-Lasting, Non See-Through",
        "Great quality",
        "Great quality, Breathable",
        "Comfortable, Great quality, Breathable, Stretch, Soft, Anti Wrinkle, Lightweight, Non See-Through",
        "Great quality, Skin-friendly",
        "Skin-friendly",
        "Long-Lasting",
        "Soft",
        "Comfortable, Great quality, Soft, Lightweight",
        "Great quality, Wind-Proof",
        "Comfortable, Great quality, Wind-Proof",
        "Warming",
        "Comfortable, Great quality, Stretch, Skin-friendly",
        "Comfortable, Lightweight",
        "Softness",
        "Wind-Proof, Warming, Comfortable",
        "Wind-Proof",
        "Breathable, Comfortable, Great quality",
        "Comfortable, Great quality, Breathable, Soft, Skin-friendly",
        "Comfortable, Great quality, Soft, 4-Way Stretch, Non See-Through",
        "Lightweight, Maximum Comfort",
        "Comfortable, Great quality, Stretch, Non See-Through",
        "Comfortable, Great quality, Soft",
        "Comfortable, Warming",
        "Great quality, Comfortable",
        "Comfortable, Great quality, Breathable, Soft",
        "Comfortable",
        "Comfortable, Great quality, Breathable, Stretch, Long-Lasting",
        "Other, Lightweight, Soft & Smooth",
        "Wind-Proof, Warming",
        "Comfortable, Soft, Non See-Through",
        "Soft, Comfortable, Great quality",
        "Breathable, Quick-Drying, Soft, Comfortable",
        "Comfortable, Great quality, Stretch, Soft, 4-Way Stretch",
        "Comfortable, Great quality, Stretch, Long-Lasting, Soft",
        "Seamless, Push Up",
        "Comfortable, Great quality, Breathable, Lightweight, Skin-friendly, Long-Lasting"
    ],  # refine + name chg
    "Closure Type": [
        "Drawstring Waist",
        "Elastic Waist",
        "Button Fly",
        "Zipper Fly"
    ],
    "Pockets": [
        "No",
        "Yes",
        "Fake Pockets"
    ],
    "Fabric": [
        "Non-Stretch, Slight Stretch",
        "Slight Stretch, Medium Stretch",
        "Slight Stretch",
        "Medium Stretch, Non-Stretch",
        "Medium Stretch, Slight Stretch",
        "Non-Stretch, Medium Stretch",
        "Non-Stretch",
        "High Stretch, Medium Stretch",
        "Non-Stretch, High Stretch",
        "Medium Stretch",
        "Medium Stretch, High Stretch",
        "High Stretch"
    ],
    "Sheer": [
        "Yes",
        "No",
        "Semi-Sheer"
    ],
    "Body": [
        "Lined",
        "Lined top, unlined bottom",
        "Yes",
        "No",
        "No, Unlined",
        "No, Yes",
        "Unlined, Lined",
        "Unlined",
        "Unlined top, lined bottom"
    ],
    "Special Features": [
        "Forest-Safe Fibers",
        "Rescued Material",
        "Recycled Material",
        "Organic Fibers",
        "Recycled Material, Organic Fibers"
    ],  # name chg
    "Temperature": [
        "Winter (<10℃/50℉)",
        "Late Fall (10-17℃/50-63℉)",
        "Spring/Fall (18-25℃/63-77℉)"
    ],  # name update remove degrees
    "Bottom Type": [
        "Shorts",
        "Pants",
        "Skort",
        "Sweatpants",
        "Skirt",
        "Leggings"
    ],
    "Style": [
        "Street, Party",
        "Straight Leg",
        "Elegant, Sexy",
        "Joggers, Pull-on Pants, Tapered",
        "Tapered",
        "Flared, Wide leg",
        "Sexy, Casual",
        "Casual, Cute, Elegant, Sexy",
        "Cute",
        "Sexy, Casual, Party",
        "Casual, Elegant",
        "Casual, Street, Party",
        "Baggy, Cargo, Stacked, Wide leg",
        "Casual, Cute, Elegant, Sexy, Boho, Party",
        "Elegant",
        "Baggy, Balloon Leg, Cargo, Stacked",
        "Baggy, Wide leg",
        "Baggy, Balloon Leg, Cargo, Carpenter-style, Stacked",
        "Balloon Leg",
        "Boho",
        "Casual, Cute, Sexy, Boho, Party",
        "Casual, Street, Work, Party",
        "Casual, Elegant, Sexy, Boho, Party",
        "Casual, Cute, Sexy, Party",
        "Baggy, Stacked",
        "Mom, Tapered",
        "Sexy, Casual, Cute",
        "Casual, Elegant, Party",
        "Casual, Cute",
        "Casual, Work",
        "Casual, Cute, Elegant, Party",
        "Elegant, Sexy, Party",
        "Cargo, Straight Leg",
        "Casual, Street, Boho",
        "Pull-on Pants, Smocked, Straight Leg",
        "Casual, Cute, Elegant, Sexy, Party",
        "Party",
        "Wide leg",
        "Baggy, Stacked, Wide leg",
        "Cute, Sexy, Party",
        "Casual, Elegant, Sexy",
        "Casual, Cute, Elegant, Boho, Party",
        "Casual, Cute, Party",
        "Simple",
        "Baggy, Balloon Leg, Stacked",
        "Jeggings",
        "Casual, Party",
        "Casual, Street",
        "Casual, Cute, Elegant",
        "Baggy, Flared",
        "Casual, Sexy, Party",
        "Baggy, Straight Leg",
        "Casual-Comfy",
        "Flared",
        "Sexy, Casual, Cute, Party",
        "Sexy, Party",
        "Casual",
        "Baggy, Bootcut",
        "Street",
        "Baggy",
        "Casual, Cute, Boho",
        "Sexy",
        "Casual, Cute, Sexy",
        "Elegant, Party",
        "Stacked, Straight Leg",
        "Casual-Comfy, Sexy",
        "Casual, Sexy",
        "Casual-Casual",
        "Casual, Elegant, Sexy, Party",
        "Baggy, Stacked, Straight Leg",
        "Casual, Cute, Elegant, Sexy, Boho",
        "Bootcut",
        "Cute, Sexy",
        "Straight Leg, Wide leg"
    ],
    "Occasion": [
        "Beach, Night Out, Wedding, Office, Babymoon, Garden, Photoshoot",
        "Night Out, Wedding, Office, Street",
        "Beach, Night Out, Wedding, Office, Photoshoot, Street",
        "Home"
    ],
    "Fit": [
        "Skinny fit",
        "Slim fit",
        "Loose fit",
        "Regular fit",
        "Relaxed fit"
    ],
    "Concept": [
        "DIVIDED",
        "DENIM, H&M+",
        "H&M EDITION",
        "DENIM"
    ],
    "Waist Rise": [
        "Low waist",
        "Ultra high waist",
        "High waist",
        "Regular waist"
    ],
    "Nice to know": [
        "Supersoft",
        "Seamless"
    ],
    "Collection": [
        "H&M ATELIER",
        "H2 HERON PRESTON H&M",
        "H&M Studio Collection",
        "A/W 2024"
    ],
    "Jeans Style": [
        "Boyfriend Fit",
        "Cargo Pants, Baggy, Boyfriend Fit",
        "Mom Fit",
        "Mom Fit, Boyfriend Fit",
        "Boyfriend Fit, Curvy",
        "Baggy",
        "Bootcut, Boyfriend Fit",
        "Baggy, Boyfriend Fit",
        "Mom Fit, Baggy, Boyfriend Fit",
        "Mom Fit, Curvy",
        "Curvy",
        "Cargo Pants, Boyfriend Fit",
        "Bootcut",
        "Cargo Pants"
    ],

}

inside_jeans = {
    'pants': {
        "Pants Material": [
            "Woven Fabric",
            "Polyester",
            "Knitted Fabric",
            "Viscose",
            "Denim"
        ],
        "Pants Body": [
            "Lined",
            "Unlined"
        ],  # name chg
        "Pants Length": [
            "Mini Shorts",
            "Long",
            "Extra Long",
            "Bermuda shorts",
            "Short"
        ],
        "Pants Composition": [
            "82.0% Cotton, 14.0% Viscose, 4.0% Polyester",
            "58% Cotton, 35% Polyester, 7% Viscose",
            "70% Cotton, 30% Polyester",
            "69% Cotton, 19% Viscose, 12% Polyester",
            "87% Cotton, 7% Polyester, 6% Viscose",
            "74.0% Cotton, 13.0% Polyester, 11.0% Viscose, 2.0% Linen",
            "100% Cotton",
            "71% Cotton, 27% Polyester, 2% Elastane",
            "80% Cotton, 13% Viscose, 5% Polyester, 2% Modal",
            "90% Cotton, 5% Polyester, 5% Viscose",
            "46% Cotton, 31% Polyester, 23% Viscose",
            "74% Cotton, 12% Polyester, 7% Viscose, 7% Lyocell",
            "70% Cotton, 14% Viscose, 13% Polyester, 3% Modal",
            "64% Cotton, 22% Polyester, 14% Viscose",
            "50% Cotton, 27% Polyester, 23% Viscose",
            "73% Cotton, 18% Polyester, 9% Viscose",
            "80% Cotton, 13% Polyester, 7% Viscose",
            "60.0% Cotton, 25.0% Polyester, 15.0% Viscose",
            "71% Cotton, 18% Polyester, 10% Viscose, 1% Polyamide",
            "78% Cotton, 14% Polyester, 7% Viscose, 1% Lyocell",
            "75% Cotton, 19% Polyester, 6% Viscose",
            "62% Cotton, 21% Polyester, 17% Viscose",
            "70% Cotton, 26% Polyester, 3% Viscose, 1% Lyocell",
            "70% Cotton, 24% Polyester, 6% Viscose",
            "78% Cotton, 9% Polyester, 8% Viscose, 5% Lyocell",
            "80% Cotton, 20% Polyester",
            "57% Cotton, 27% Polyester, 16% Viscose",
            "79% Cotton, 20% Polyester, 1% Viscose",
            "55% Cotton, 31% Polyester, 12% Viscose, 2% Elastane",
            "72.0% Cotton, 15.0% Viscose, 12.0% Polyester, 1.0% Modal",
            "67% Cotton, 26% Polyester, 6% Viscose, 1% Elastane",
            "70% Cotton, 16% Polyester, 14% Viscose",
            "68% Cotton, 16% Polyester, 14% Viscose, 2% Modal",
            "85% Cotton, 15% Polyester",
            "48% Cotton, 27% Polyester, 25% Viscose",
            "66% Cotton, 29% Polyester, 5% Viscose",
            "75% Cotton, 12% Viscose, 9% Polyester, 4% Modal",
            "86% Cotton, 8% Viscose, 6% Polyester",
            "51% Cotton, 34% Polyester, 8% Viscose, 4% Acrylic, 3% Polyamide",
            "60% Cotton, 27% Polyester, 10% Lyocell, 3% Viscose",
            "64% Cotton, 21% Viscose, 14% Polyester, 1% Modal",
            "66% Cotton, 30% Polyester, 2% Elastane, 2% Viscose",
            "68% Cotton, 17% Viscose, 14% Polyester, 1% Modal",
            "51% Cotton, 28% Viscose, 21% Polyester",
            "63% Cotton, 34% Polyester, 2% Viscose, 1% Modal",
            "52% Cotton, 28% Polyester, 20% Viscose",
            "89% Cotton, 6% Polyester, 5% Viscose",
            "48% Cotton, 35% Polyester, 17% Viscose",
            "62.0% Cotton, 21.0% Polyester, 10.0% Viscose, 6.0% Lyocell, 1.0% Modal",
            "91% Cotton, 5% Viscose, 4% Polyester",
            "76% Cotton, 18% Polyester, 6% Viscose",
            "43% Cotton, 28% Polyester, 13% Lyocell, 12% Viscose, 2% Acrylic, 2% Polyamide",
            "54% Cotton, 27% Polyester, 19% Viscose",
            "77% Cotton, 12% Polyester, 9% Viscose, 2% Lyocell",
            "79% Cotton, 14% Polyester, 7% Viscose",
            "95% Polyester, 5% Elastane",
            "93% Cotton, 4% Polyester, 3% Viscose",
            "52% Cotton, 24% Polyester, 24% Viscose"
        ],
    },
    'outwear':{
        "Outerwear Sleeve Length": [
            "Sleeveless",
            "Long Sleeve",
            "Wrist-Length Sleeve",
            "Short Sleeve"
        ],
        "Outerwear Length": [
            "Regular",
            "Short"
        ],
        "Outerwear Body": [
            "Lined",
            "Unlined"
        ],
        "Outerwear Material": [
            "Woven Fabric",
            "Denim"
        ],
        "Outerwear Composition": [
            "76% Cotton, 13% Viscose, 11% Polyester",
            "58% Cotton, 35% Polyester, 7% Viscose",
            "87% Cotton, 7% Polyester, 6% Viscose",
            "88% Cotton, 7% Polyester, 5% Viscose",
            "100% Cotton",
            "46% Cotton, 31% Polyester, 23% Viscose",
            "70% Cotton, 14% Viscose, 13% Polyester, 3% Modal",
            "100% Polyester",
            "64% Cotton, 22% Polyester, 14% Viscose",
            "50% Cotton, 27% Polyester, 23% Viscose",
            "73% Cotton, 18% Polyester, 9% Viscose",
            "78% Cotton, 14% Polyester, 7% Viscose, 1% Lyocell",
            "62% Cotton, 21% Polyester, 17% Viscose",
            "70% Cotton, 26% Polyester, 3% Viscose, 1% Lyocell",
            "78% Cotton, 9% Polyester, 8% Viscose, 5% Lyocell",
            "79% Cotton, 20% Polyester, 1% Viscose",
            "68% Cotton, 16% Polyester, 14% Viscose, 2% Modal",
            "85% Cotton, 15% Polyester",
            "48% Cotton, 27% Polyester, 25% Viscose",
            "75% Cotton, 12% Viscose, 9% Polyester, 4% Modal",
            "86% Cotton, 8% Viscose, 6% Polyester",
            "51% Cotton, 34% Polyester, 8% Viscose, 4% Acrylic, 3% Polyamide",
            "60% Cotton, 27% Polyester, 10% Lyocell, 3% Viscose",
            "64% Cotton, 21% Viscose, 14% Polyester, 1% Modal",
            "63% Cotton, 34% Polyester, 2% Viscose, 1% Modal",
            "52% Cotton, 28% Polyester, 20% Viscose",
            "91% Cotton, 5% Viscose, 4% Polyester",
            "43% Cotton, 28% Polyester, 13% Lyocell, 12% Viscose, 2% Acrylic, 2% Polyamide",
            "77% Cotton, 12% Polyester, 9% Viscose, 2% Lyocell",
            "52% Cotton, 24% Polyester, 24% Viscose"
        ],

    },
    'skirts':{
        "Skirts Length": [
            "Midi",
            "Mini",
            "Short",
            "Long"
        ],
        "Skirts Material": [
            "Woven Fabric",
            "Fabric",
            "Denim"
        ],

    }
}