"Shirts":{
        "Composition":"fix",
        "Sleeve Length":[
            "Short sleeve",
            "Long Sleeve",
            "Sleeveless",
            "Short Sleeve",
            "Three Quarter Length Sleeve",
            "Half Sleeve",
            "Long sleeve",
            "Wrist-Length Sleeve"
        ],
        "Neckline":[
            "Peak Lapels",
            "Notched",
            "Funnel Neck",
            "Cardigan Collar",
            "Polo",
            "High Neck",
            "Waterfall",
            "Choker Neck",
            "Square Neck",
            "Henley",
            "Tie Neck",
            "Hooded",
            "V neck",
            "Stand Collar",
            "Deep V Neck",
            "Contrast Collar",
            "Lapel",
            "Flounce Collar",
            "Round Neck",
            "Pile Heap Collar",
            "V-neck",
            "Baseball Collar",
            "Boat Neck",
            "Shawl Collar",
            "Shirt Collar",
            "Sweetheart",
            "Off the Shoulder",
            "Collar"
        ],
        "Color":"fix",
        "Sleeve Type":[
            "Drop Shoulder",
            "Cold Shoulder",
            "Batwing Sleeve",
            "Flounce Sleeve",
            "Kimono Sleeve",
            "Flare Sleeve",
            "Raglan Sleeve",
            "Suit Sleeve",
            "Split Sleeve",
            "Roll Up Sleeve",
            "Puff Sleeve",
            "Bishop Sleeve",
            "Regular Sleeve",
            "Shirt Sleeve"
        ],
        "Material":[
            "Nylon",
            "Wool",
            "Chiffon",
            "Embroidery",
            "Glitter",
            "Cotton, Corduroy",
            "Polyester",
            "Polyurethane",
            "Seersucker",
            "Cotton, Twill",
            "Flannel",
            "Sequins",
            "Silk",
            "Knitwear",
            "Suedette",
            "Tweed",
            "Flannelette",
            "Viscose",
            "Twill",
            "Cotton",
            "Mesh Fabric",
            "Linen",
            "Woven Fabric",
            "Cotton, Oxford",
            "Fabric",
            "Felt",
            "Lace",
            "Teddy",
            "Satin",
            "Jersey",
            "Bouclé",
            "Denim",
            "Rib knit",
            "Lyocell",
            "Cotton, Denim",
            "The Special Effect Printing",
            "Cotton, Dobby",
            "Knitted Fabric",
            "Crepe",
            "Velvet",
            "Cotton, French Terry",
            "PU Leather",
            "Composite Fabric",
            "Rayon, Satin",
            "Corduroy"
        ],
        "Hem Shaped":[
            "Regular",
            "Asymmetrical",
            "Tight Hem",
            "Slit",
            "Flared"
        ],
        "Type":[
            "Shirt",
            "Tunic",
            "Shirt, Top",
            "Top"
        ],
        "Fit Type":[
            "Loose",
            "Slim Fit",
            "Regular Fit",
            "Oversized"
        ],
        "Length":[
            "Regular length",
            "Long",
            "Regular",
            "Crop",
            "Short"
        ],
        "Pattern Type":"fix",
        "Style":[
            "Street, Party",
            "Casual, Vintage",
            "Cute",
            "Casual, Elegant",
            "Casual, Street, Party",
            "Casual, Elegant, Work",
            "Casual, Elegant, Vintage, Work",
            "Elegant",
            "Casual, Cute, Elegant, Sexy, Street, Boho, Party",
            "Casual, Street, Boho, Vintage, Work, Party",
            "Casual, Boho",
            "Casual, Street, Boho, Party",
            "Boho",
            "Casual, Street, Work, Party",
            "Casual, Cute, Elegant, Work, Party",
            "Casual, Elegant, Party",
            "Casual, Work",
            "Casual, Cute, Street",
            "Boho, Party",
            "Party",
            "Casual, Street, Boho",
            "Overshirt, Shirt Jacket",
            "Casual, Elegant, Sexy",
            "Casual, Cute, Party",
            "Casual, Street, Vintage, Party",
            "Elegant, Work",
            "Casual, Party",
            "Casual, Street",
            "Casual, Vintage, Work",
            "Vintage",
            "Casual, Street, Work",
            "Street, Boho",
            "Casual, Elegant, Street",
            "Casual, Cute, Sexy, Work",
            "Casual",
            "Work",
            "Street",
            "Vintage, Work",
            "Casual, Elegant, Work, Party",
            "Sexy",
            "Casual, Elegant, Street, Boho",
            "Casual, Elegant, Sexy, Street",
            "Casual, Sexy",
            "Work, Party",
            "Casual, Elegant, Street, Party",
            "Overshirt",
            "Casual, Elegant, Vintage, Party"
        ],
        "Fabric":[
            "Non-Stretch, Slight Stretch",
            "Slight Stretch, Medium Stretch",
            "Slight Stretch",
            "Non-Stretch, Medium Stretch",
            "Non-Stretch",
            "Medium Stretch",
            "High Stretch"
        ],
        "Placket":[
            "Chinese Frog Button",
            "Pullover",
            "Open Front",
            "Single Button",
            "Single Breasted",
            "Lace-up",
            "Zipper",
            "Double Breasted"
        ],
        "Sheer":[
            "Yes",
            "No",
            "Semi-Sheer"
        ],
        "Pockets":[
            "No",
            "Yes"
        ],
        "Body":[
            "Lined",
            "Unlined",
            "No",
            "No, Unlined"
        ],
        "Features":[
            "Stretch, Soft",
            "Breathable, Soft",
            "Breathable, Quick-Drying, Lightweight, Skin-friendly, Comfortable, Great quality",
            "Lightweight, Skin-friendly, Soft & Lightweight, Soft, Comfortable",
            "Lightweight, Soft",
            "Breathable, Lightweight, Soft",
            "Warming, Absorbs Sweat, Breathable, Lightweight, Stretch, 100% Natural, Soft & Lightweight, Warm & Breathable, Comfortable",
            "Quick-Drying, Tencel™",
            "100% Natural, Skin-friendly",
            "Breathable, Soft, Anti Wrinkle",
            "Lightweight, 100% Natural, Skin-friendly, Long-Lasting, Soft, Comfortable, Great quality",
            "Quick-Drying, Skin-friendly, Anti Wrinkle",
            "Soft & Lightweight",
            "Comfortable, Great quality, Warming, Breathable, Lightweight, Cooling, Soft & Lightweight, Warm & Breathable, Soft, Feels Like Skin",
            "Breathable, Skin-friendly",
            "Absorbs Sweat, Anti-UV, Lightweight",
            "Maximum Comfort, 100% Natural, Skin-friendly, Warm & Breathable, Soft, Comfortable, Great quality",
            "Lightweight, Stretch, Comfortable, Great quality",
            "Warming, Absorbs Sweat, Breathable, Lightweight",
            "Maximum Comfort, Skin-friendly, Warm & Breathable, Soft, Comfortable, Great quality",
            "Warming, Breathable, Cooling, Feels Like Skin, Maximum Comfort, Skin-friendly, Warm & Breathable, Soft, Comfortable, Great quality",
            "Maximum Comfort, Skin-friendly, Soft & Lightweight",
            "Stretch",
            "Breathable, Skin-friendly, Anti Wrinkle",
            "Absorbs Sweat, Breathable, Comfortable, Great quality",
            "Breathable, Lightweight, Skin-friendly",
            "Lightweight, Skin-friendly, Long-Lasting, Soft & Lightweight, Tencel™",
            "Absorbs Sweat, Breathable, Skin-friendly, Soft & Lightweight",
            "Lightweight, Maximum Comfort, Skin-friendly, Soft & Lightweight, Soft",
            "Breathable, Lightweight, Stretch, Skin-friendly, Soft",
            "Comfortable, Great quality",
            "Lightweight, Soft & Lightweight",
            "Breathable, Quick-Drying, Lightweight, Cooling, Feels Like Skin, Maximum Comfort, Skin-friendly, Soft & Lightweight, Soft, Comfortable, Great quality, Anti Wrinkle",
            "Anti Wrinkle",
            "Lightweight, Skin-friendly, Soft, Comfortable, Great quality",
            "Warming, Stretch, Comfortable, Great quality",
            "Warming, Breathable, Lightweight, Cooling, Feels Like Skin, Soft & Lightweight, Warm & Breathable, Soft, Comfortable, Great quality",
            "Lightweight, Skin-friendly",
            "Breathable, Anti Wrinkle",
            "Quick-Drying, Lightweight, Skin-friendly",
            "Breathable",
            "Warming, Stretch, Maximum Comfort, Warm & Breathable",
            "Lightweight, Stretch, Maximum Comfort, Great quality",
            "Warming, Comfortable, Great quality",
            "Stretch, Skin-friendly, Soft & Lightweight",
            "Lightweight, Skin-friendly, Comfortable",
            "High Stretch, Stretch, Maximum Comfort, Skin-friendly, Soft & Lightweight",
            "Breathable, Stretch",
            "Waterproof, Stretch, Three Proofing Fabric",
            "Soft, Great quality",
            "Lightweight",
            "Great quality",
            "Lightweight, Great quality",
            "Absorbs Sweat, Breathable, Lightweight",
            "High Stretch, Lightweight, Skin-friendly",
            "Breathable, Lightweight, Soft, Comfortable",
            "Soft",
            "Breathable, Lightweight, Maximum Comfort, Comfortable, Great quality",
            "Maximum Comfort, 100% Natural, Skin-friendly, Soft & Lightweight, Soft",
            "Quick-Drying, Lightweight, Soft & Lightweight",
            "Warming",
            "Breathable, Stretch, Skin-friendly",
            "Absorbs Sweat, Quick-Drying, Lightweight, Soft & Lightweight",
            "Absorbs Sweat, Breathable",
            "Comfortable, Great quality, Antibacterial, Breathable, Quick-Drying, Lightweight",
            "Soft, Comfortable, Great quality, Anti Wrinkle",
            "Breathable, Soft & Lightweight",
            "Quick-Drying, Lightweight",
            "Antibacterial, Quick-Drying, Lightweight",
            "Skin-friendly, Long-Lasting, Soft & Lightweight, Soft, Comfortable",
            "Warming, Breathable, Cooling, Maximum Comfort, Long-Lasting, Warm & Breathable, Comfortable, Great quality",
            "Lightweight, Stretch, Soft",
            "High Stretch, Breathable, Soft & Lightweight",
            "Breathable, Lightweight, Comfortable",
            "Comfortable",
            "Breathable, Lightweight, Maximum Comfort",
            "Comfortable, Great quality, Breathable, Quick-Drying, Lightweight, Cooling, Maximum Comfort, Skin-friendly, Soft & Lightweight, Soft, Anti Wrinkle, Feels Like Skin",
            "Absorbs Sweat, Breathable, Quick-Drying",
            "Absorbs Sweat, Breathable, Stretch, Skin-friendly, Soft & Lightweight",
            "Breathable, Quick-Drying, Lightweight",
            "Breathable, Lightweight",
            "Soft, Comfortable",
            "Breathable, Lightweight, Stretch"
        ],
        "Lined For Added Warmth":[
            "Yes",
            "No"
        ],
        "Chest pad":[
            "Yes",
            "No Padding"
        ],
        "Belt":[
            "Yes",
            "No"
        ],
        "Special Features":[
            "Recycled Material"
        ],
        "Tops Sleeve Length":[
            "Short Sleeve",
            "Long Sleeve, Long Sleeve",
            "Short Sleeve, Short Sleeve"
        ],
        "Tops Material":[
            "Woven Fabric",
            "Woven Fabric, Woven Fabric"
        ],
        "Tops Length":[
            "Regular",
            "Regular, Regular"
        ],
        "Fit":[
            "Relaxed fit",
            "Regular fit",
            "Loose fit",
            "Slim fit"
        ],
        "Size":[
            "Back: Length: 71.5 in. (Size L), Shoulder: Width: 51.0 in. (Size L), Sleeve: Length: 65.5 in. (Size L)",
            "Sleeve: Length: 29.5 in. (Size L), Shoulder: Width: 53.0 in. (Size L), Back: Length: 74.5 in. (Size L)",
            "Sleeve: Length: 27.5 in. (Size L), Back: Length: 78.0 in. (Size L)",
            "Shoulder: Width: 53.0 in. (Size L), Back: Length: 74.5 in. (Size L), Sleeve: Length: 65.5 in. (Size L)",
            "Back: Length: 77.5 in. (Size L), Sleeve: Length: 64.0 in. (Size L), Shoulder: Width: 57.5 in. (Size L)",
            "Shoulder: Width: 56.5 in. (Size L), Sleeve: Length: 26.0 in. (Size L), Back: Length: 73.5 in. (Size L)",
            "Sleeve: Length: 66.0 in. (Size L), Shoulder: Width: 52.5 in. (Size L), Back: Length: 72.5 in. (Size L)",
            "Sleeve: Length: 66.5 in. (Size L), Shoulder: Width: 51.5 in. (Size L), Back: Length: 78.0 in. (Size L)",
            "Sleeve: Length: 67.0 in. (Size L), Back: Length: 72.0 in. (Size L), Shoulder: Width: 51.5 in. (Size L)",
            "Shoulder: Width: 52.0 in. (Size L), Sleeve: Length: 26.0 in. (Size L)",
            "Sleeve: Length: 67.0 in. (Size L), Shoulder: Width: 51.0 in. (Size L), Back: Length: 76.0 in. (Size L)",
            "Sleeve: Length: 67.0 in. (Size L), Shoulder: Width: 49.5 in. (Size L)",
            "Back: Length: 71.5 in. (Size L), Sleeve: Length: 67.5 in. (Size L), Shoulder: Width: 52.5 in. (Size L)",
            "Sleeve: Length: 66.0 in. (Size L), Back: Length: 71.5 in. (Size L), Shoulder: Width: 52.5 in. (Size L)",
            "Shoulder: Width: 55.0 in. (Size L), Sleeve: Length: 27.5 in. (Size L)",
            "Sleeve: Length: 64.0 in. (Size L), Shoulder: Width: 57.5 in. (Size L), Back: Length: 80.0 in. (Size L)",
            "Sleeve: Length: 26.5 in. (Size L), Front: Length: 67.5 in. (Size L)",
            "Shoulder: Width: 57.5 in. (Size L), Sleeve: Length: 27.5 in. (Size L), Back: Length: 78.0 in. (Size L)",
            "Sleeve: Length: 64.5 in. (Size L), Shoulder: Width: 54.5 in. (Size L), Back: Length: 78.0 in. (Size L)",
            "Shoulder: Width: 57.5 in. (Size L), Sleeve: Length: 62.0 in. (Size L), Back: Length: 76.5 in. (Size L)",
            "Sleeve: Length: 65.0 in. (Size L), Shoulder: Width: 53.0 in. (Size L), Back: Length: 74.0 in. (Size L)",
            "Shoulder: Width: 58.0 in. (Size L), Front: Length: 66.5 in. (Size L), Sleeve: Length: 24.5 in. (Size L)",
            "Sleeve: Length: 66.0 in. (Size L), Back: Length: 78.5 in. (Size L), Shoulder: Width: 51.5 in. (Size L)",
            "Shoulder: Width: 52.0 in. (Size L), Back: Length: 79.0 in. (Size L)",
            "Sleeve: Length: 66.5 in. (Size L), Back: Length: 64.5 in. (Size L), Shoulder: Width: 50.0 in. (Size L)",
            "Shoulder: Width: 52.5 in. (Size L), Back: Length: 74.0 in. (Size L)",
            "Front: Length: 68.5 in. (Size L), Sleeve: Length: 24.5 in. (Size L)",
            "Sleeve: Length: 28.5 in. (Size L), Shoulder: Width: 52.0 in. (Size L), Back: Length: 73.0 in. (Size L)",
            "Sleeve: Length: 28.5 in. (Size L), Back: Length: 73.0 in. (Size L)",
            "Front: Length: 72.5 in. (Size L), Shoulder: Width: 55.0 in. (Size L), Sleeve: Length: 27.5 in. (Size L)",
            "Shoulder: Width: 52.0 in. (Size L), Sleeve: Length: 26.0 in. (Size L), Front: Length: 76.0 in. (Size L)",
            "Sleeve: Length: 26.5 in. (Size L)",
            "Sleeve: Length: 67.5 in. (Size L), Shoulder: Width: 51.5 in. (Size L), Back: Length: 73.5 in. (Size L)",
            "Sleeve: Length: 66.0 in. (Size L), Shoulder: Width: 51.0 in. (Size L), Back: Length: 73.5 in. (Size L)",
            "Sleeve: Length: 65.0 in. (Size L), Shoulder: Width: 54.5 in. (Size L), Back: Length: 75.5 in. (Size L)",
            "Shoulder: Width: 56.5 in. (Size L), Sleeve: Length: 64.5 in. (Size L), Back: Length: 73.5 in. (Size L)",
            "Shoulder: Width: 58.5 in. (Size L), Back: Length: 104.0 in. (Size L), Sleeve: Length: 62.5 in. (Size L)",
            "Sleeve: Length: 66.0 in. (Size L), Shoulder: Width: 52.5 in. (Size L), Back: Length: 74.0 in. (Size L)",
            "Sleeve: Length: 65.0 in. (Size L), Shoulder: Width: 54.5 in. (Size L), Back: Length: 76.5 in. (Size L)",
            "Front: Length: 73.0 in. (Size L), Sleeve: Length: 67.5 in. (Size L), Shoulder: Width: 49.5 in. (Size L)",
            "Back: Length: 79.0 in. (Size L), Sleeve: Length: 68.5 in. (Size L), Shoulder: Width: 50.5 in. (Size L)",
            "Sleeve: Length: 65.5 in. (Size L), Front: Length: 73.5 in. (Size L), Shoulder: Width: 50.0 in. (Size L)",
            "Sleeve: Length: 66.0 in. (Size L), Shoulder: Width: 53.5 in. (Size L), Back: Length: 76.5 in. (Size L)",
            "Sleeve: Length: 67.0 in. (Size L), Shoulder: Width: 51.0 in. (Size L), Back: Length: 75.5 in. (Size L)",
            "Back: Length: 70.5 in. (Size L), Sleeve: Length: 64.0 in. (Size L)",
            "Sleeve: Length: 65.0 in. (Size L), Shoulder: Width: 57.5 in. (Size L), Back: Length: 73.0 in. (Size L)",
            "Sleeve: Length: 25.5 in. (Size L), Front: Length: 72.0 in. (Size L)",
            "Back: Length: 70.5 in. (Size L), Sleeve: Length: 67.0 in. (Size L), Shoulder: Width: 54.5 in. (Size L)",
            "Back: Length: 79.0 in. (Size L), Sleeve: Length: 68.5 in. (Size L)",
            "Shoulder: Width: 52.5 in. (Size L), Sleeve: Length: 66.5 in. (Size L), Back: Length: 73.5 in. (Size L)",
            "Shoulder: Width: 51.0 in. (Size L), Back: Length: 77.5 in. (Size L), Sleeve: Length: 66.5 in. (Size L)",
            "Shoulder: Width: 51.0 in. (Size L), Sleeve: Length: 28.0 in. (Size L), Back: Length: 74.0 in. (Size L)",
            "Sleeve: Length: 66.5 in. (Size L), Back: Length: 79.0 in. (Size L)",
            "Sleeve: Length: 67.5 in. (Size L), Back: Length: 79.0 in. (Size L)"
        ],
        "imported":[
            "Yes"
        ],
        "Detailed Description":[
            "Brown, Patterned",
            "Dark gray, Solid-color",
            "Khaki green, Solid-color",
            "Light beige/black/blue, Floral",
            "Cream, Solid-color",
            "Dark khaki green, Solid-color",
            "Dark blue/white, Checked",
            "Light blue, Solid-color",
            "White, Solid-color",
            "Dark gray/white",
            "Light denim blue, Solid-color",
            "Dark green/beige, Striped",
            "Black, Solid-color",
            "Beige, Solid-color",
            "White/gray, Striped",
            "Light brown/black/white, Checked",
            "Light blue, Striped",
            "Sage green, Solid-color",
            "Burgundy, Solid-color",
            "Dark beige melange",
            "Dark brown, Solid-color",
            "Gray, Solid-color",
            "Light beige, Solid-color",
            "Brown, Solid-color",
            "Black",
            "Taupe, Solid-color",
            "Navy blue/cream",
            "Pink, Solid-color",
            "Navy blue, Solid-color",
            "Dark beige, Solid-color"
        ],
        "Collar":[
            "Band Collar",
            "Resort Collar",
            "Notched Lapels",
            "Button-down Collar",
            "Turn-down Collar"
        ],
        "Nice to know":[
            "Lined",
            "H&M Premium Selection",
            "Padded"
        ],
    },