Tshirts = {
    "Fit": [
        "Regular fit",
        "Loose fit",
        "Oversized",
        "Slim fit"
    ],
    "Composition": "fix",
    "Sleeve Length": [
        "Short sleeve",
        "Wrist-Length Sleeve",
        "Sleeveless",
        "Extra-Long Sleeve",
        "Short Sleeve",
        "Cap Sleeve",
        "Three Quarter Length Sleeve",
        "Half Sleeve",
        "Long sleeve",
        "Long Sleeve"
    ],
    "Neckline": [
        "Queen Anne Neckline",
        "Scoop Neck",
        "Cowl Neck",
        "Notched",
        "Funnel Neck",
        "High Neck",
        "Polo",
        "Cardigan Collar",
        "Mandarin Collar",
        "Square Neck",
        "Henley",
        "Halter",
        "Low Cut Neck",
        "Hooded",
        "Tie Neck",
        "V neck",
        "Stand Collar",
        "Deep V Neck",
        "Straps",
        "Flounce Collar",
        "Round Neck",
        "Cold Shoulder",
        "Pile Heap Collar",
        "Baseball Collar",
        "Spaghetti Strap",
        "Boat Neck",
        "Keyhole Neckline",
        "Overlap Collar",
        "Shirt Collar",
        "Heart Shape",
        "Sweetheart",
        "Asymmetrical Neck",
        "Off the Shoulder",
        "Collar",
        "One Shoulder"
    ],
    "Length": [
        "Regular length",
        "Long",
        "Regular",
        "Micro Crop",
        "Long, Regular",
        "Crop",
        "Short"
    ],
    "Material": [
        "Embroidery",
        "Glitter",
        "Polyester",
        "Sequins",
        "Knitwear",
        "Cotton, Jersey",
        "Flocking",
        "Flannelette",
        "Cotton",
        "Mesh Fabric",
        "Woven Fabric",
        "Fabric",
        "Jersey",
        "Lace",
        "Satin",
        "Rib knit",
        "Knitted Fabric",
        "Cotton, Pique",
        "Velvet",
        "Composite Fabric"
    ],
    "Style": [
        "Sexy, Casual",
        "Cute",
        "Casual, Elegant",
        "Casual, Street, Party",
        "Elegant",
        "Casual, Street, Work, Party",
        "Casual, Cute",
        "Casual, Cute, Elegant, Party",
        "Sexy, Casual, Cute, Elegant, Party",
        "Party",
        "Boxy",
        "Polo shirt",
        "Casual, Party",
        "Casual, Street",
        "Tank Top",
        "Casual, Street, Work",
        "Casual",
        "Work",
        "Street",
        "Sexy",
        "Henley Shirt"
    ],
    "Collar": [
        "Turn-down Collar",
        "Henley Collar"
    ],
    "Color": "fix",
    "Sleeve Type": [
        "Drop Shoulder",
        "Cold Shoulder",
        "Batwing Sleeve",
        "Flounce Sleeve",
        "Flare Sleeve",
        "Leg-of-mutton Sleeve",
        "Layered Sleeve",
        "Puff Sleeve",
        "Roll Up Sleeve",
        "Bishop Sleeve",
        "Regular Sleeve",
        "Raglan Sleeve"
    ],
    "Fit Type": [
        "Oversized",
        "Loose, Slim Fit",
        "Loose",
        "Slim Fit",
        "Regular Fit",
        "Regular Fit, Slim Fit"
    ],
    "Pockets": [
        "Yes",
        "No"
    ],
    "Fabric": [
        "Non-Stretch, Slight Stretch",
        "Slight Stretch",
        "Medium Stretch, Slight Stretch",
        "Non-Stretch",
        "Slight Stretch, High Stretch",
        "Medium Stretch",
        "Medium Stretch, High Stretch",
        "High Stretch"
    ],
    "Sheer": [
        "Yes",
        "No",
        "Semi-Sheer"
    ],
    "Hem Shaped": [
        "Regular",
        "Pleated",
        "Asymmetrical",
        "Tight Hem",
        "Slit",
        "Flared"
    ],
    "Lined For Added Warmth": [
        "Yes",
        "No"
    ],
    "Features": [
        "Great quality, Soft & Lightweight",
        "Great quality, Comfortable, Antibacterial, Lightweight, Skin-friendly, Long-Lasting, Soft & Lightweight, Soft",
        "Comfortable, Lightweight",
        "Warm & Breathable",
        "Lightweight, Soft",
        "Great quality, Stretch, Soft",
        "Absorbs Sweat, Quick-Drying, Maximum Comfort",
        "Great quality, Skin-friendly, Long-Lasting, Soft & Lightweight",
        "Warming, Stretch, Soft",
        "Comfortable, Thermo-Regulating, Maximum Comfort, 100% Natural, Soft",
        "Great quality, Skin-friendly, Soft",
        "High Stretch",
        "Lightweight, Maximum Comfort, Skin-friendly, Soft & Lightweight, Soft",
        "Quick-Drying",
        "Great quality, Comfortable, Absorbs Sweat, Breathable, Stretch, Soft, Anti Wrinkle",
        "Great quality, Comfortable, Stretch, Maximum Comfort, Soft & Lightweight, Soft",
        "Great quality, Absorbs Sweat, Breathable, Maximum Comfort, Skin-friendly",
        "Breathable, 100% Natural",
        "Lightweight, Skin-friendly, Soft",
        "Absorbs Sweat",
        "Great quality, Skin-friendly, Warm & Breathable",
        "Great quality, Lightweight, Stretch, Maximum Comfort, Soft & Lightweight, Soft",
        "Comfortable, Wind-Proof",
        "Lightweight",
        "Great quality, Soft",
        "Comfortable, Soft",
        "Great quality",
        "Great quality, Comfortable, Breathable, Lightweight, Maximum Comfort, Skin-friendly, Long-Lasting, Soft",
        "Great quality, Comfortable",
        "Comfortable",
        "Great quality, Skin-friendly",
        "Comfortable, Absorbs Sweat, Breathable, Stretch, Soft",
        "Great quality, Absorbs Sweat, Breathable, Maximum Comfort, Soft",
        "Maximum Comfort, Warm & Breathable, Soft",
        "Great quality, Absorbs Sweat, Breathable, Stretch, Maximum Comfort, Soft & Lightweight, Soft",
        "Skin-friendly",
        "Soft",
        "Stretch",
        "Great quality, Absorbs Sweat, Breathable, Stretch, Soft",
        "Absorbs Sweat, Breathable, Maximum Comfort, Soft",
        "Breathable",
        "Great quality, Comfortable, Absorbs Sweat, Breathable, Stretch, 100% Natural, Skin-friendly, Soft",
        "Lightweight, Maximum Comfort, Soft & Lightweight, Soft",
        "100% Natural, Skin-friendly, Soft",
        "Feels Like Skin"
    ],
    "Body": [
        "Lined top, unlined bottom",
        "Lined",
        "No",
        "No, Unlined",
        "Unlined"
    ],
    "Special Features": [
        "Forest-Safe Fibers",
        "Recycled Material",
        "Recycled Material, Forest-Safe Fibers"
    ],
    "Occasion": [
        "Beach, Sports, Home, Street",
        "Sports, Home, Street",
        "Beach, Night Out, Sports, Office, Home, Street",
        "Beach, Night Out, Home, Street",
        "Beach, Night Out, Home",
        "Beach, Office, Home, Street",
        "Beach, Sports, Street",
        "Beach",
        "Home",
        "Sports, Home, Garden, Street",
        "Home, Garden",
        "Night Out",
        "Home, Street",
        "Night Out, Office, Home, Street",
        "Beach, Office, Home",
        "Beach, Sports, Office, Home, Photoshoot, Street",
        "Beach, Night Out, Sports, Home, Street",
        "Beach, Night Out, Office, Street",
        "Beach, Home, Street",
        "Sports, Office, Home, Street",
        "Night Out, Sports, Office, Street",
        "Office, Home, Street",
        "Sports, Office",
        "Sports, Home",
        "Night Out, Sports, Office, Home, Street",
        "Office",
        "Street",
        "Sports, Street",
        "Sports, Office, Home, Garden, Street",
        "Sports, Office, Home, Photoshoot, Street"
    ],
}

top = {
    "Tops Sleeve Length": [
        "Long Sleeve, Long Sleeve, Long Sleeve",
        "Short Sleeve",
        "Short Sleeve, Short Sleeve, Short Sleeve",
        "Long Sleeve",
        "Long Sleeve, Long Sleeve",
        "Short Sleeve, Short Sleeve"
    ],
    "Tops Material": [
        "Knitted Fabric, Knitted Fabric, Knitted Fabric",
        "Fabric, Fabric",
        "Knitted Fabric, Knitted Fabric",
        "Polyester",
        "Knitted Fabric"
    ],
    "Tops Length": [
        "Short",
        "Regular",
        "Crop, Crop",
        "Regular, Regular, Regular",
        "Short, Short",
        "Crop, Crop, Crop",
        "Crop",
        "Regular, Regular"
    ]
}