Watches= {
    "Calendar Type": [
        "Day-Month",
        "Date",
        "Date-Week",
        "Day, Date, Month, Year & Moon Phase",
        "NO",
        "time",
        "Day-Date-Month-Moon Phase",
        "Two Hands",
        "Day-Date-Month-Year",
        "Date-Month",
        "Digital",
        "Day-Date-Month",
        "Day, Date, Month & Year",
        "Chronograph",
        "No Calendar",
        "Date-Week-Month",
        "No",
        "Day-Date",
        "Time",
        "Date-Moon Phase",
        "Day"
    ],
    "Date First Available": "fix",  # what it means
    "Part Number": "fix",
    "Band Colour": "fix",  # must add
    "ASIN": "fix",  # whats this
    "Product Dimensions": "fix",
    "Special Features": "fix",
    "Case Thickness": "fix",  # must add
    "Department": [
        "Womens",
        "Unisex Kids",
        "Mens",
        "Unisex Child",
        "Boys & Girls",
        "Couple",
        "girls",
        "women",
        "Boys",
        "unisex",
        "mens",
        "Baby Girls",
        "womens",
        "baby-girls",
        "Men & Women",
        "Unisex",
        "children",
        "Women and Girls",
        "Women Girls",
        "Mens , Boys",
        "unisex-child",
        "Boys & Gilrs",
        "boys",
        "Baby Boys",
        "unisex-adult",
        "Men, Boys",
        "Men, Women",
        "Girls",
        "Mens And Boys",
        "Unisex Adult",
        "men",
        "Men",
        "Women"
    ],
    "Display Type": [
        "2Time, ALARM , DATE ,WEEK ,EL LIGHT",
        "Analog",
        "Multifunction",
        "time teacher",
        "Digital",
        "chronograph",
        "AMOLED",
        "time, date, stopwatch",
        "LED",
        "analogue",
        "3Time, ALARM , DATE ,WEEK ,EL LIGHT",
        "TIME,DATE,STOPWATCH",
        "Chronograph",
        "Analog-Digital",
        "Pointer type"
    ], # refine - reduce
    "Manufacturer": "fix",  # manuf or brand - must add
    "Case Material": [
        "Gold-tone Metal",
        "Resin",
        "Gold-plated Steel",
        "Gold",
        "Alloy Steel",
        "Stainless Steel",
        "Wood",
        "Synthetic",
        "Fiber",
        "ABS + Zinc alloy",
        "ABS Composite",
        "Stainless SteelFashion Cart",
        "Synthetic Leather",
        "Leather",
        "Mineral Glass",
        "Buckle",
        "Carbon",
        "Acrylonitrile Butadiene Styrene",
        "Rose Gold",
        "Copper",
        "Genuine Leather & Stainless Steel",
        "Glass",
        "Metal Alloy",
        "Silicone",
        "Stainless Steel, Gold",
        "Plastic",
        "Brass",
        "Aluminium",
        "Silver",
        "PU",
        "Metal",
        "Rose Gold-tone Stainless Steel",
        "Premium Metal",
        "ABS + TPU",
        "Gold Plated",
        "Yellow Gold",
        "Rose Gold Stainless Steel",
        "Genuine Leather",
        "Titanium",
        "Rubber",
        "Silicon",
        "Alloy",
        "Silver-tone Metal",
        "Ceramic",
        "Palladium",
        "TR90",
        "Polycarbonate"
    ],  # cut short + name chg - case
    "Crystal Material": [
        "Resin",
        "Tempered Glass",
        "Stainless Steel",
        "Sapphire Crystal",
        "Mineral Glass",
        "Glass",
        "Mineral Crystal",
        "Hardlex",
        "Synthetic-sapphire glass",
        "Plastic",
        "Brass",
        "PU",
        "Sapphire",
        "Metal",
        "Glass Fiber",
        "Mineral",
        "Synthetic Sapphire",
        "Crystal",
        "No",
        "Rubber",
        "Acrylic",
        "steel"
    ],
    "Movement": [
        "Japanese Automatic",
        "Hand Driven",
        "Womens Standard",
        "Mechanical",
        "Automatic",
        "Japanese Quartz",
        "Mechanical Hand Wind",
        "Japanese",
        "DIGITAL",
        "Mechanical Automatic",
        "HMT",
        "Solar",
        "Light Powered",
        "Electronic",
        "Analog",
        "Digital",
        "Quartz",
        "Mechanical Manual",
        "Chinese Automatic",
        "Analog-digital",
        "universal moment",
        "Chinese Quartz",
        "Swiss Quartz",
        "No"
    ],
    "Band size": [
        "Womens",
        "Children Standard",
        "Womens Short",
        "22",
        "24cm",
        "Womens Standard",
        "Mens Extralong",
        "2",
        "Womens Extralong",
        "Mens Long",
        "18mm",
        "0.8",
        "Yellow",
        "8.5mm",
        "Standard",
        "Unisex",
        "12",
        "Mens Standard",
        "Free Size",
        "Regular",
        "210",
        "Childrens",
        "Womens Long",
        "20",
        "Women $ Girls",
        "Childrens Long",
        "Brown",
        "Adjustable",
        "3.2",
        "Women Standard",
        "2.2",
        "22mm",
        "20mm",
        "1.4",
        "Women"
    ],  # need fix
    "Case Diameter": "fix",  # must add
    "Brand": "fix",  # must add
    "Case Shape": [
        "Rectangle",
        "Round",
        "Rectangular",
        "Hexagonal",
        "Octogonal",
        "Clover",
        "Asymmetrical",
        "Shaped",
        "Round & Square",
        "Tonneau",
        "Round::Square",
        "NO",
        "Diamond",
        "Square",
        "5",
        "Octagonal",
        "Oval"
    ],
    "Bezel Material": [
        "No Bazel",
        "Resin",
        "Gold",
        "Alloy Steel",
        "Stainless Steel",
        "LEATHER",
        "Wood",
        "Aluminum",
        "Stainless Steel Case",
        "ABS+zinc alloy",
        "Crystal material glass",
        "Stainless Case",
        "Leather",
        "Carbon / Bio-based resin",
        "Copper",
        "Genuine Leather & Stainless Steel",
        "Rose Gold",
        "Glass",
        "NO Bazel Function",
        "Silicone",
        "Rhinestone",
        "Resin / Stainless steel",
        "Fiber Font Case,Stainless Steel Back",
        "Chrome",
        "Bio-based resin",
        "Plastic",
        "Brass",
        "Aluminium",
        "Resin / Bio-based Resin",
        "Carbon Fibre",
        "Silver",
        "No bezel Available",
        "Metal",
        "No bezel available",
        "yellow gold",
        "Fiber font",
        "Platinum",
        "Silocone",
        "No Bezel Available",
        "No bazel",
        "Fiber Font Stainless Steel Case",
        "Genuine Leather",
        "Titanium",
        "No",
        "Rubber",
        "Silicon",
        "Ceramic",
        "Polycarbonate"
    ],
    "Band Material": [
        "Nylon",
        "Thermoplastic Polyurethane (TPU)",
        "STAINLES STEEL",
        "Gold-tone Metal",
        "Grey",
        "Resin",
        "Stainlee Steel",
        "Gold",
        "",
        "Alloy Steel",
        "Stainless Steel",
        "Polyurethane",
        "Wood",
        "Other Material",
        "Multicolour",
        "Silica gel",
        "Stainless Steel RoseGold plated",
        "Leather",
        "pearl",
        "Stainless steel strap",
        "Battery Powered",
        "Copper",
        "Genuine Leather & Stainless Steel",
        "Rose Gold",
        "synthetic",
        "Metal Alloy",
        "Silicone",
        "Sheet metal",
        "Stainless Steel Gold Plated",
        "Stainless Steel::Synthetic Leather",
        "Stainless Steel, Gold",
        "Fabric",
        "Plastic",
        "Brass",
        "Silver",
        "Aluminium",
        "Metal",
        "#N/A",
        "Mesh",
        "Yellow Gold",
        "Lether",
        "Titanium",
        "Black",
        "Rubber",
        "Faux Leather",
        "Alloy",
        "Mesh Belt Stainless Steel",
        "skin",
        "Stainless Steel Silver Plated",
        "Ceramic",
        "Acrylic",
        "Chain",
        "Polycarbonate"
    ],
    "Clasp": [
        "Normal",
        "Tang Buckle",
        "Snap",
        "meganet",
        "Hook & Loop",
        "bangle",
        "Grey",
        "Gold",
        "Needle Buckle",
        "matel",
        "Foldable Clasp",
        "Push Buckle clasp",
        "velcro",
        "Deployment Clasp With Safety",
        "Push Button Foldover Clasp With Safety",
        "Clasp",
        "Bracelet",
        "Bangle",
        "Green",
        "Butterfly / Hidden Folding",
        "Buckle",
        "Butterfly double buckle",
        "Deployment Clasp",
        "Triple Fold Clasp",
        "Tang Buckle Clasp",
        "Expansion Band",
        "Push Button Clasp",
        "Fancy Clasp",
        "Structure",
        "Fold-Over Clasp with Hidden Double Push Button",
        "Pin Buckle",
        "Box Safety Clasp",
        "Jewelled Buckle",
        "Push Buckle",
        "Sliding Clasp",
        "As Per Description",
        "Magnetic Clasp",
        "Jewel Clasp",
        "Push Button",
        "Push Button Hidden Clasp",
        "bracelet watch",
        "Long Chain",
        "Push Lock",
        "Adjustable Clasp",
        "Single Locking Fold-Over Clasp",
        "Push Button Deployment Clasp",
        "Silver",
        "Lobster Claw Clasp",
        "Folding Clasp With Safety",
        "Double Locking Foldover Clasp",
        "Flip Clasp",
        "Stainless Steel Buckle",
        "Three-fold clasp with push button release",
        "Pin buckle",
        "Jewellery pin",
        "Foldover Clasp With Push Button",
        "Magnet strap",
        "Leather Buckle(For LS)",
        "Jewelry Clasp",
        "No Calendar",
        "Hook Buckle",
        "Black",
        "Lock",
        "PUSH-BUTTON-CLASP",
        "Box With Tongue And Safety",
        "Small Body Push Type",
        "Hook and Loop",
        "Push Button clasp",
        "Hidden Clasp",
        "Meganet",
        "Foldover Clasp",
        "Butterfly double snap button"
    ],
    "Included Components": [
        "Resin",
        "Warranty Card, Watch",
        "Watch Box",
        "2 watches",
        "Watch, Manual",
        "Date Display Watch",
        "no",
        "Earrings, Necklace, Pendant",
        "silicon slap band bracelet watch",
        "1 Piece of mechanical wristwatch",
        "Automatic Watch",
        "Analog Watch",
        "Watch, stainless steel tapered bracelet, folding clasp, and sapphire crystal glass",
        "links remove tool, user guide",
        "Pocket watch, Chain",
        "box packing bracelet watch",
        "Band",
        "User Manual",
        "1 Piece Quartz Watch",
        "Strap adjustment tool",
        "Watch, View*1, Original watch box*1, Instruction Manual*1, Warranty card*1",
        "Combo watch set",
        "1 Watch",
        "Analog",
        "1 Piece Cuff Wristwatch",
        "1 Pcs Bracelet Watch",
        "watch, original box, instruction manual, cleaning cloth, strap adjuster",
        "WATCH",
        "Wristwatch",
        "1 Pcs Women Wrist Watches",
        "Belt Clip",
        "Battery, Band",
        "1 Piece Watch",
        "Men Digital Sports Watch",
        "Quartz movement, SR626 battery",
        "Battery",
        "Digital watch",
        "User Manual, Watch",
        "Analog Wrist Watch",
        "Analog Watch with Date Function",
        "Belt Clip, Battery, Watch, Box, Band",
        "pocket watch, chain, jewelry packaging box",
        "1 Piece Skeleton Automatic Watch",
        "bracelet gift for girls",
        "Gift box, 2 year warranty",
        "Warranty Card, Watch, Manual",
        "Chain",
        "[User Manual, Original Box]",
        "Watch, Bangle",
        "silicon slap band bracelet",
        "Watch"
    ],  # may remove
    "Collection": [
        "Hip-hop",
        "Commodore",
        "Lifestyle",
        "Islamic Ladies Collection",
        "Facet",
        "Lexington",
        "Facet Brilliant",
        "Harlowe",
        "Facet Strass",
        "Formal",
        "Fiber",
        "Fashion Casual Watch",
        "Race",
        "Mechanical Skeleton Automatic",
        "SITARA RISE & SHINE",
        "270",
        "Classic",
        "Fashion",
        "Atacama Field",
        "Swiftsure",
        "Attivo",
        "Vendme",
        "Bonne Nouvelle",
        "BRACELET WATCH COLLECTION",
        "Tiro",
        "Glowing Light & Waterproof",
        "Emery",
        "Metro S",
        "Broadway",
        "Gaillon",
        "luxury",
        "Analog",
        "Sport",
        "Belleville",
        "Attrazione",
        "2024",
        "Infinity",
        "LeWy 9",
        "Sport Tourer",
        "6",
        "Rylee",
        "Luxury",
        "Sports",
        "SS Collection",
        "Panthon",
        "Bear Grylls Survival",
        "5",
        "Navy SEAL Foundation",
        "Ocean Upcycle",
        "ANANYA",
        "Watch Ring",
        "230",
        "sports",
        "Digital BackLight Series",
        "Casual",
        "All",
        "Hybrid",
        "Silver Diamond",
        "I.N.O.X.",
        "Seven Color Digital Watch",
        "Unika",
        "ASGARD",
        "WEDDING AND PARTYWEAR",
        "North Star",
        "Vivienne",
        "casual",
        "Pigalle",
        "Casual Wear"
    ],  # imp
    "Shape": [
        "Round",
        "Rectangular",
        "Hexagonal",
        "Octagon",
        "Asymmetrical",
        "Square",
        "Oval"
    ],  # imp
    "Age Range Description": [
        "Adult",
        "Kid"
    ],  # imp
    "Product Features": [
        "Time Display",
        "Waterproof",
        "Always On Display",
        "Shock Resistant",
        "Sleep Monitoring, Shock Resistant, Heart Rate Monitor",
        "Lightweight"
    ],
    "Colour": [
        "BLACK & PINK",
        "Black",
        "Orange",
        "BLACK",
        "Green",
        "Multicolor",
        "Yellow "
    ],  # name chg
    "Brand Name": [
        "Wristflix",
        "Generic",
        "LUHIMO",
        "PATTERN CART",
        "PIRASO",
        "ZOVUTA",
        "DOUBLERUN"
    ],  # imp
    "Band Color": [
        "BLACK & PINK",
        "Black",
        "Multicolour",
        "black",
        "orange",
        "White",
        "Multicolor"
    ],  # imp
    "Box Contents": [
        "Digital Watch",
        "Wristwatch",
        "LED WATCH",
    ],  # name chg - watch type
    "Band Material Type": [
        "Rubber",
        "Silicone",
        "Plastic",
        "plastic"
    ],  # imp
    "Target Audience": [
        "Unisex Kids",
        "Baby Boys, Boys, Baby Girls, Girls, Unisex Kids",
        "Unisex Teen",
        "Unisex Adult",
        "Men"
    ],  # imp
    "Style": [
        "Modern",
        "strap",
        "Casual"
    ],
    "Clasp Type": [
        "Buckle",
        "Tang Buckle",
        "Deployment Clasp",
        "Push Button Deployment Clasp",
        "Needle Buckle",
        "Hook Buckle",
        "PUSH BOTTOM BUCKLE",
        "Hook and Loop",
        "buckle",
        "Box Safety Clasp",
        "Sliding Clasp",
        "Magnet Clasp"
    ],
    "Special Feature": [
        "Time Display",
        "Waterproof",
        "Distance Tracker, Calori, Alarm Clock",
        "Not Tested On Animals, Scented",
        "Always On Display",
        "Alarm, Ultra Thin",
        "Shock Resistant",
        "Sleep Monitoring, Shock Resistant, Heart Rate Monitor",
        "9H Surface Hardness, Scratch Resistant",
        "Lightweight"
    ],  # name chg
    "Metal": [
        "Stainless Steel Pu",
        "Stainless Steel",
        "Alloy",
        "PU Leather Alloy",
    ],
    "Stone": [
        "Stainless Steel Pu",
        "Stainless Steel",
        "Quartz",
        "Rhinestone",
    ],
    "Theme": [
        "Fashion",
        "Sports",
        "Military"
    ],
    "Band Style1 - Band Style5": [
        "Modern",
        "Antique",
        "Classic",
        "strap"
    ],  # name chg
    "Power Source": [
        "Solar Powered",
        "Battery",
        "Battery Powered",
        "Light",
        "Motion",
        "Solar"
    ],
    "Batteries Included": [
        "Yes",
        "No"
    ],
    "Batteries Required": [
        "Yes",
        "No"
    ],
    "Strap Material": [
        "Fabric",
        "Resin",
        "Plastic",
        "Stainless Steel",
        "Rubber",
        "Metal",
        "Silicon",
        "Alloy",
        "Synthetic",
        "Ceramic",
        "Silicone",
        "PU Leather",
        "Canvas",
        "Leather",
        "Polycarbonate"
    ],
    "Glass Material": [
        "Mineral Glass",
        "Plastic",
        "Acetate Glass",
        "Sapphire Crystal",
        "Acrylic"
    ],
    "Occasion": [
        "Casual",
        "Everyday Essentials",
        "Formal",
        "Sports",
        "Party"
    ],
    "Dial Pattern": [
        "Textured",
        "Skeleton",
        "Embellished",
        "Printed",
        "Patterned",
        "Mother of Pearl",
        "Solid"
    ],
    "Dial Shape": [
        "Round",
        "Rectangular",
        "Diamond",
        "Square",
        "Asymmetric",
        "Oval"
    ],
    "Features": [
        "Multilingual Menu",
        "Multiple Time Zone",
        "Reset Time",
        "Multifunction",
        "Multi Function",
        "Plain 3-Hand",
        "Tachymeter",
        "Chronograph"
    ],  # name chg
    "Dial Material": [
        "Nylon",
        "Resin",
        "Plastic",
        "Acetate",
        "Brass",
        "Titanium",
        "Stainless Steel",
        "Rubber",
        "Glass",
        "Metal",
        "Silicon",
        "Alloy",
        "Ceramic",
        "Bioceramic",
        "Polycarbonate"
    ],
    "Strap Closure": [
        "Butterfly",
        "Foldover and Butterfly",
        "Button",
        "Tang",
        "Foldover"
    ],
    "Strap Style": [
        "Wrap Around",
        "Serpentine Strap",
        "Bracelet Style",
        "Textured",
        "Regular",
        "Embellished",
        "Braided",
        "Cuff"
    ],
    "Watch Weight in g": "fix",
    "Make": [
        "Non-Swiss Made",
        "Swiss Made"
    ],
    "Type": [
        "Regular",
        "Hybrid",
        "Smart"
    ],
    "Scratch Resistance": [
        "No",
        "Yes"
    ],
    "Sustainable": [
        "Regular",
        "Sustainable"
    ],
    "Display": [
        "Digital",
        "Analogue",
        "Analogue and Digital"
    ],
    "Features 3": [
        "Glow in the Dark Inlays",
        "Multiple Time Zone",
        "Reset Time",
        "Calendar",
        "Stopwatch",
        "Multi Function",
        "Date Aperture",
        "Alarm",
        "Chronograph"
    ],  # name chg - may drop
    "Features 2": [
        "Glow in the Dark Inlays",
        "Reset Time",
        "Calendar",
        "Stopwatch",
        "Multi Function",
        "Tachymeter",
        "Date Aperture",
        "Alarm",
        "Chronograph"
    ],  # name chg - may drop
    "Case Material1 - Case Material2": [
        "Plastic",
        "Brass",
        "Stainless Steel",
        "Stainless Steel & Plastic",
        "Silicone"
    ],  # name chg
    "Movement Type": [
        "Automatic",
        "Digital",
        "Quartz"
    ],
    "Strap Type": [
        "Strap",
        "STRAP",
        "BRACELET",
        "MESH BRACELET",
        "Bracelet",
        "Two Piece Strap",
        "bracelet"
    ],
    "Dial Type": [
        "Analog + Digital",
        "Digital",
        "Analog"
    ],
    "Strap Color": [
        "Grey",
        "Gold",
        "Peach",
        "Green",
        "Taupe",
        "Rose Gold",
        "Orange",
        "Yellow",
        "Tan",
        "Red",
        "Silver",
        "Purple",
        "Multi-Color",
        "Blue",
        "Burgundy",
        "Beige",
        "White",
        "Cream",
        "Pink",
        "Black",
        "Brown",
        "Navy Blue",
        "Clear"
    ],  # refine
    "Pack Size": [
        "Single",
        "Pack of 2"
    ],
    "Dial Color": [
        "Grey",
        "Gold",
        "Off White",
        "Peach",
        "Green",
        "Maroon",
        "Rose Gold",
        "Orange",
        "black",
        "Yellow",
        "Turquoise",
        "Red",
        "Silver",
        "Purple",
        "Blue",
        "Multi-Color",
        "Beige",
        "White",
        "Olive",
        "Cream",
        "Pink",
        "Black",
        "Brown",
        "Navy Blue"
    ],  # refine
    "Display Technology": [
        "LCD",
        "AMOLED",
        "Analog"
    ],
    "Material": [
        "Alloy Steel",
        "Glass",
        "Metal",
        "Plastic"
    ],  # name chg - watch material or drop
    "Device interface - primary": [
        "Buttons",
        "Touchscreen"
    ],  # imp + name change
    "Pattern": [
        "Floral",
        "Classic"
    ],  # may keep
}
